name: Do a Duolingo lesson

on:
  workflow_dispatch:
    inputs:
      lessons:
        default: 1
        description: 'Number of lessons to be completed'
        required: false
        type: number

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: node index.js
        env:
          DUOLINGO_JWT: "eyJOeXAiOiJKV1QiLCJhbGciOiJIUz|1NiJ9.eyJleHAiOjYzMDcyMDAwMDAw|mIhdCl6MCwic3ViljoxOTYyOTсwOTZ9.Vg7sVasаKUЗ7UJIXQHyAuхjt0jH4¡rРH5-VAY12eXK8"
          LESSONS: ${{ inputs.lessons }}
